  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    env_file:
      - ./services/mariadb/mariadb.env
    volumes:
      - ./volumes/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"

