version: '2'
services:
  influxdb:
    image: "influxdb:latest"
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    env_file:
      - influxdb.env
    volumes:
      - $PWD/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:6.3.6
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - grafana.env
    volumes:
      - $PWD/grafana/data:/var/lib/grafana
      - $PWD/grafana/logs:/var/log/grafana


  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - $PWD/nodered/data:/data

