services:
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9080:8080"
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: 5m
        max-file: "3"
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
    volumes:
      - "./volumes/grafana/data:/var/lib/grafana"
      - "./volumes/grafana/log:/var/log/grafana"
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: 5m
        max-file: "3"
  dashmachine:
    image: "rmountjoy/dashmachine:latest"
    container_name: dashmachine
    volumes:
      - "./volumes/dashmachine/user_data:/dashmachine/dashmachine/user_data"
    ports:
      - "5000:5000"
    restart: unless-stopped
  diyhue:
    container_name: diyhue
    image: "diyhue/core:latest"
    ports:
      - "8070:80/tcp"
      - "1900:1900/udp"
      - "1982:1982/udp"
      - "2100:2100/udp"
    environment:
      - IP=%LAN_IP_Address%
      - MAC=%LAN_MAC_Address%
    volumes:
      - "./volumes/diyhue/:/opt/hue-emulator/export/"
    restart: unless-stopped
    networks:
      - iotstack_nw
  gitea:
    container_name: gitea
    image: "kunde21/gitea-arm:latest"
    restart: unless-stopped
    ports:
      - "7920:3000/tcp"
      - "2222:22/tcp"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - "./volumes/gitea/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: 5m
        max-file: "3"
  espruinohub:
    container_name: espruinohub
    image: humbertosales/espruinohub-docker-rpi
    network_mode: host
    privileged: true
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
networks:
  iotstack_nw:
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.60.0/24
