  webthings_gateway:
    image: mozillaiot/gateway:latest
    container_name: webthings_gateway
    networks:
      - hosts_nw
    ports: # Changing this won't do anything. Change the port in local.json.
    - 8083:8083
    - 8084:8084
    #devices:
    # - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./volumes/webthings_gateway/share:/home/node/.mozilla-iot
    logging:
      options:
        max-size: "5m"
        max-file: "3"
