  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '8090:80'
      - '4439:443'
      - '5901:5900'
    volumes:
       - ./volumes/deconz/:/root/.local/share/dresden-elektronik/deCONZ
    #devices:
      #ConBee II uncomment next line
      #- /dev/ttyACM0
      #ConBee uncomment next line
      #- /dev/ttyUSB0
      #RaspBee uncomment next line
      #- /dev/ttyAMA0 or /dev/ttyS0
    environment:
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=changeme
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
