  gitea:
    container_name: gitea
    # image: gitea/gitea:latest
    image: kapdap/gitea-rpi
    restart: unless-stopped
    user: "0"
    ports:
      - "7920:3000/tcp"
      - "2222:22/tcp"
    env_file:
      - ./services/gitea/gitea.env
    volumes:
      - ./volumes/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    # environment:
    #   - USER_UID=1000
    #   - USER_GID=1000
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"
