  diyhue:
    container_name: diyhue
    image: diyhue/core:latest
    ports:
      - "8070:80/tcp"
      - "1900:1900/udp"
      - "1982:1982/udp"
      - "2100:2100/udp"
      # - "443:443/tcp"
    environment:
      - IP=your_Pis_IP_here
      - MAC=your_Pis_MAC_here
    volumes:
       - ./volumes/diyhue/:/opt/hue-emulator/export/
    restart: unless-stopped
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"
