zigbee2mqtt_assistant:
  container_name: zigbee2mqtt_assistant
  image: carldebilly/zigbee2mqttassistant
  restart: unless-stopped
  env_file:
    - ./services/zigbee2mqtt_assistant/zigbee2mqtt_assistant.env
  ports:
    - 8880:80
  environment:
    - VIRTUAL_HOST=~^zigbee2mqtt_assistant\..*\.xip\.io
    - VIRTUAL_PORT=8880
