  homebridge:
    container_name: homebridge
    image: oznu/homebridge:no-avahi-arm32v6
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=4040
    volumes:
      - ./volumes/homebridge:/homebridge
    ports: # Changing this won't do anything. Change the port in environment.HOMEBRIDGE_CONFIG_UI_PORT. Ensure values are synced
      - "4040:4040"
    network_mode: host
    # networks:
    #   - hosts_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"