  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - ./services/postgres/postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"