  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    environment:
      # - INFLUXDB_DB=mydb
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      # - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      # - INFLUXDB_ADMIN_USER=myadminuser
      # - INFLUXDB_ADMIN_PASSWORD=myadminpassword
      - INFLUXDB_USER=nodered
      - INFLUXDB_USER_PASSWORD=nodered
      # - INFLUXDB_READ_USER=myreaduser
      # - INFLUXDB_READ_USER_PASSWORD=myreadpassword
      # - INFLUXDB_WRITE_USER=mywriteuser
      # - INFLUXDB_WRITE_USER_PASSWORD=mywritepassword
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"
