  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    environment:
      # - INFLUXDB_DB=mydb
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      # - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=influxadminuser
      - INFLUXDB_ADMIN_PASSWORD=%randomAdminPassword% # %randomAdminPassword% is overwritten during preBuild hook
      - INFLUXDB_USER=influxuser
      - INFLUXDB_USER_PASSWORD=%randomPassword% # %randomPassword% is overwritten during preBuild hook
      - INFLUXDB_READ_USER=influxreaduser
      - INFLUXDB_READ_USER_PASSWORD=%randomReadPassword% # %randomReadPassword% is overwritten during preBuild hook
      - INFLUXDB_WRITE_USER=influxwriteuser
      - INFLUXDB_WRITE_USER_PASSWORD=%randomWritePassword% # %randomWritePassword% is overwritten during preBuild hook
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"
