  duplicati:
    container_name: Duplicati
    restart: unless-stopped
    image: lsioarmhf/duplicati
    network_mode: host
    #ports:
    #  - 8200:8200
    volumes:
      - /:/source
      - ./volumes/duplicati:/config
      - /etc/localtime:/etc/localtime:ro
 
