  blynk_server:
    build: ./services/blynk_server/.
    container_name: blynk_server
    restart: unless-stopped
    ports:
      - 8070:8080
      - 1900:8441
      - 9443:9443
    volumes:
      - ./volumes/blynk_server/data:/data

