  plex:
    image: linuxserver/plex
    container_name: plex
    networks:
      - hosts_nw
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
    volumes:
      - ./volumes/plex/config:/config
      #- ~/mnt/HDD/tvseries:/tv
      #- ~/mnt/HDD/movies:/movies
      - ./volumes/plex/transcode:/transcode
    restart: unless-stopped
